import Head from 'next/head'
import styles from '../styles/Home.module.css'

function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.containerChild}>
        <section className={styles.section}>
          <form action="/api/checkout-session" method="POST">
          <img className={styles.image} src ="https://i.pinimg.com/564x/c5/e5/96/c5e5965d040214c91ad429494ac83b14.jpg"
              alt="meme-nude-tiger"
              width="210px"
              height="210px"
              style={{borderRadius: "50%"}} />
            <div className={styles.name}>IMG Chill</div>
            <div className={styles.price}>Price: $81</div>
            <div className={styles.count}>Quantity: 1</div>
            <button id={styles.btn}>Buy</button>
          </form>
        </section>
      </div>
    </div>
  )
}

export default Home
